version: '3.5'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    networks:
      - vorto
    ports:
      - "5432:5432"
    volumes:
      - ./sql/coffee.sql:/docker-entrypoint-initdb.d/coffee.sql
    environment:
      POSTGRES_PASSWORD: admin*123
  api:
    image: anadk/vorto-coffeeshop-api:1.0
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    networks:
      - vorto
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin*123
    depends_on:
      - postgres
  # DB admin tool
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - vorto
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

networks:
  vorto:
    name: vorto
